### ISSUE TITLE
Implement Github templates

### ISSUE THREAD

**Issue by Soarnir** [DIT113-V22/group-04#11]
## Description

The use of Github templates will greatly improve readability and consistency across any area we can implement them.

This first iteration of templates will include pull requests and issue creation focused on user stories and acceptance criteria.

## Clarifying checklist

- [x] Templates of issues will ensure the issue includes both the user story and the acceptance criteria.
- [x] Templates of pull requests include a description of the pull requests, issues closes and dependencies added

**Comment by platisd** [comment]
:+1:

**Comment by Kev049** [comment]
We have implemented a basic set of templates and have found them very helpful while using them. Although we may add/modify templates in the future, we are satisfied with our current templates for now and are closing this issue.
