### ISSUE TITLE
Save movement instructions

### ISSUE THREAD

**Issue by Kev049** [DIT113-V22/group-04#46]
## User story 4.2
As a user, I want to save the path I draw, so that I can execute it later and the car can follow the same path again.

## Acceptance Criteria

Given the user has finished drawing the path,
When the user clicks the save button,
Then the equivalent movement instructions of the drawn path are saved.

## Checklist

- [x] The movement instructions are saved in SQLite database
- [x] The movement instructions are executed in the exact same was as the actual run.

---

Part of [Epic Feature 4](https://github.com/DIT113-V22/group-04/wiki/EF-4-Saving-Paths)

**Comment by Kev049** [comment]
Due to time and technical constraints, the development team has decided to not implement this user story.

**Comment by MortBA** [comment]
Did not have enough time to implement the feature and sadly removed it.
