### ISSUE TITLE
Android application allows to draw path

### ISSUE THREAD

**Issue by sejalkan** [DIT113-V22/group-04#5]
## User story 2.1
The system shall allow the users to draw paths for the car to follow.

## Acceptance criteria
Scenario: The user is on the draw control screen

Given that the user has the application successfully working on an android device and is on the draw control screen,
When the user wants to drive a car in a specific manner,
Then the application will allow the user to draw that path for the car.

## Clarifying checklist
- [x] The app allows the user to draw a path
- [x] As the user drags their finger accross the canvas, a path is drawn
- [x] The path is drawn on a grid-based canvas

[Part of Epic Feature 2](https://github.com/DIT113-V22/group-04/wiki/EF-2-Drawing-Paths)

**Comment by Kev049** [comment]
This is not a vertical User Story as it was meant to solely deal with the UI and thus, is marked as invalid and is being closed.
