### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by Soarnir** [DIT113-V22/group-04#51]
## Description

We're now past the halfway point of the project and have established most of the technologies used, a proper LICENSE.md file is needed to adequately cover the technologies used in this software.

## Checklist

- [x] LICENSE.md file is added

**Comment by RuthgerD** [comment]
The project is already licensed under MIT though ?

**Comment by AeroStun** [comment]
https://github.com/DIT113-V22/group-04/blob/master/LICENSE

**Comment by Soarnir** [comment]
You have a very valid point, luckily I have a scheduled appointment with my eye doctor in the coming weeks where I will bring this blatant blindness up...

**Comment by Soarnir** [comment]
Closing this issue as a license.md already exists, and I completely missed it.
