### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by Soarnir** [DIT113-V22/group-04#52]
## Description

Issue for tracking wiki updates. Update checklist with what needs to be done, and check them off as they are completed.

## Checklist
- [x] Add [table of contents](https://github.com/DIT113-V22/group-04/wiki)
- [x] Update [App Preview](https://github.com/DIT113-V22/group-04/wiki/App-Preview)
- [x] Update [EF2](https://github.com/DIT113-V22/group-04/wiki/EF-2-Drawing-Paths)
- [x] Update [EF3](https://github.com/DIT113-V22/group-04/wiki/EF-3-Manual-Control)
- [x] Update [EF4](https://github.com/DIT113-V22/group-04/wiki/EF-4-Saving-Paths)
- [x] Update [EF5](https://github.com/DIT113-V22/group-04/wiki/EF-5-Connectivity)
- [x] Update [Installation & Setup](https://github.com/DIT113-V22/group-04/wiki/Installation-&-Setup)
- [x] Update [milestones ](https://github.com/DIT113-V22/group-04/milestones)

**Comment by Kev049** [comment]
The SRS requirements in each of the Wikis have been updated. A description has also been written for each of the milestones to add further clarity.
