### ISSUE TITLE
Create diagrams

### ISSUE THREAD

**Issue by Soarnir** [DIT113-V22/group-04#57]
## Description

A couple of diagrams will go a long way to show anyone the structural make-up of our project and provide clarity using standardised, UML diagrams like component and deployment diagrams.

## Checklist

- [x]  The diagram(s) made should be clear and follow the standard design rules.
- [x]  The diagrams should have a clear title and good naming conventions.
- [x]  A component diagram of the entire system is created.
- [x]  A deployment diagram of the entire system is created.

**Comment by RuthgerD** [comment]
godspeed
