### ISSUE TITLE
Saved Paths UI

### ISSUE THREAD

**Issue by YukiMina14** [DIT113-V22/group-04#9]
## Description:
As a user, I want the application to save previously travelled paths so that the car can drive on the same path again instead of giving the same information twice.

## Acceptance Criteria:
Given that the user might want to save the current drawn or manually driven path for future use,
When the user draws or manually drives a path,
Then the application will allow the user to save the path to the saved path list.

**Comment by Kev049** [comment]
This is not a vertical User Story as it deals solely with the UI and thus, is marked as invalid and is being closed.
